# hugo module configuration

# metarex has migrated from docsy to the fohuw theme
# this theme is  migrating away from bootstrap towards a full fomantic site
# with simplified shortcuts that are created with partials to reduce custom code.

# CLI upgrade to the latest theme:   hugo mod get github.com/mrmxf/fohuw@main

hugoVersion:
  extended: true
  min: v0.144.2
imports:
  - path: github.com/mrmxf/fohuw
    disable: false
# uncomment line below for temporary local development of module
replacements: "github.com/mrmxf/fohuw->../../pub-mrmxf/fohuw"
