# GitHub Workflow for building and deploying a Hugo site to GitHub Pages
# needs secrets.MRX_DOCKER_USR - the account username for docker hub
# needs secrets.MRX_DOCKER_PAT - the account password for docker hub
# needs vars.MRX_DOCKER_NS - the account namespace for docker hub e.g. mrmxf
name: Build Metarex staging website to container

on:
  # Runs on all pushes
  push:
    branches:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# global environment
env:
  # For maximum backward compatibility with Hugo modules
  HUGO_ENV: production

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages:    write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    environment: metarex
    steps:
      -
        name: Install clog
        run: curl https://mrmxf.com/get/clog | bash
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
      -
        name: Install tools
        run: |
          clog install yq
          clog install hugo
          sudo snap install dart-sass
          if [[ -f package-lock.json || -f npm-shrinkwrap.json ]] ; then
            npm ci  || true
          else
            npm i || true
          fi
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PAT }}
      -
        name: Build & push
        run: clog build
      # -
      #   name: Build and push - ARM
      #   uses: docker/build-push-action@v5
      #   with:
      #     # important that we use path context otherwise no output!
      #     context:   .
      #     push:      true
      #     tags: |
      #           "${{ vars.MRX_DOCKER_NS  }}/${{ env.IMAGE  }}-arm:${{ env.vCODE }}"
      #     platforms: linux/arm64
      # -
      #   name: Build and push - AMD
      #   uses: docker/build-push-action@v5
      #   with:
      #     # important that we use path context otherwise no output!
      #     context:   .
      #     push:      true
      #     tags: |
      #           "${{ vars.MRX_DOCKER_NS  }}/${{ env.IMAGE  }}-amd:${{ env.vCODE }}"
      #     platforms: linux/amd64
